### ISSUE TITLE
Exception thrown from ManagerReader.cs (need help)

### ISSUE THREAD

**Issue by squaregear** [AsterNET/AsterNET#107]
I've been seeing the following:

`Unhandled Exception:
 
System.SystemException: Unable to run: socket is null.
   at AsterNET.Manager.ManagerReader.Run() in 
e:\Projects\Github\AsterNET\Asterisk.2013\Asterisk.NET\Manager\ManagerReader.cs:line 197
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, 
Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, 
Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

You can see the line that throws this error at ManagerReader.cs, line 197. It looks like this happens when connect() (in ManagerConnection.cs) launches a new thread, but mrSocket is somehow null in ManagerReader.cs. But this exception gets throws in a separate thread, so I can't catch it and handle the error. It just crashes my application. 

So I have two questions. First, how do I prevent this from happening? Am I doing something wrong with how I connect or reconnect? Second, is it possible to catch this somehow and try the connection again?

**Comment by skrusty** [comment]
Are you using source or the nuget package?

**Comment by squaregear** [comment]
The nuget package

**Comment by squaregear** [comment]
Is there a significant difference between the nuget package and the source code?

**Comment by squaregear** [comment]
Does anyone know what may be causing that "Unable to run: socket is null" error?

Also, is there another place I should be going with questions like this? I couldn't find a mailing list or equivalent for AsterNet.

**Comment by skrusty** [comment]
we have an IRC channel, and this issue area. 

Without more information, it's very hard to understand the issue you're having. DO you have any further output from the debug window on this issue?

**Comment by squaregear** [comment]
It seems to happen most often when there is a lot of activity on the Asterisk box it's connected to. I'm assuming there is some kind of network drop and then this happens when it is reconnecting. Looking at ManagerReader.cs and ManagerConnection.cs, though, I don't even see how it gets to that line without mrSocket being set. Is there somewhere else that starts that ManagerReader thread? Or is there some .Net trick I don't know to catch an exception thrown from someone else's thread? 

I'll keep digging and see if I can figure out more specifics about what leads us there.

**Comment by squaregear** [comment]
I've recreated the error with a simple example. You can see it at:
https://gist.github.com/squaregear/80821130d221727c3836dba3224bf93e
I have a thread running that periodically checks if the connection is still good and tries to reconnect if it isn't. That seems to be the problem. If I take the logout/login actions out of the loop, it sometimes finds the connection down but the AsterNet logic reconnects it. Should I just keep my hands off of reconnecting? 

It used to be that you had to send pings to the Asterisk box every so often or it would close the connection on you. That's what my loop was originally meant to do. Do you not have to do that any more, or is that being handled by the library for me? I'm in the process of upgrading a system using *very* out of date versions of both Asterisk and AsterNet (It's actually using Asterisk.Net if that tells you something). Is the practice now that I should just login my ManagerConnection and then just leave it alone? Can you count on that for applications that run for months at a time?

**Comment by skrusty** [comment]
You don't have to send the PING, it's done for you.

Yes, I would let AsterNET handle the re-connection; you shouldn't need to worry about handling that.

Quite why you get the error I am unsure, might be handle to give the full exception stack if you can, just for reference.

Cheers

**Comment by squaregear** [comment]
The whole stack that I get is shown at the top. It's thrown from within a separate thread, so ThreadStart() is the bottom of the stack.

**Comment by Deantwo** [comment]
So, all your sample code is doing is logging in and out over and over again if `IsConnected()` is false?

`IsConnected()` is checking the socket state, so it is not very reliable. It can become false while the socket is lost and trying to reconnect.

I also seem to recall an issue with reusing the same `ManagerConnection` instance over and over again, better to just null it and reinitialize it if you need to log out and back in.

**Comment by Deantwo** [comment]
Maybe we should just remove `IsConnected()`, or replace it with a bool that is set to true on login and false on logout or final disconnect.

**Comment by Deantwo** [comment]
I found the note in my code about the issue with reusing the same `ManagerConnection` instance over and over again.
```
_ami = new ManagerConnection(); // Timeout exception is thrown when attempting to reconnect after having been connected before. Creating a new instance each time fixes this.
```
We should probably fix this.
