### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by rex644** [AsterNET/AsterNET#112]
I am getting an error connecting. I use FreePBX. I tried adding a user to Admin>Administrators. I also tried the user/secert from manager.conf

The error:

```
Fail: Authentication failed


   at AsterNET.Manager.ManagerConnection.login(Int32 timeout) in e:\Projects\Github\AsterNET\Asterisk.2013\Asterisk.NET\Manager\ManagerConnection.cs:line 1410

   at AsterNET.Manager.ManagerConnection.Login() in e:\Projects\Github\AsterNET\Asterisk.2013\Asterisk.NET\Manager\ManagerConnection.cs:line 1713

   at DialerAstro.Form1.Connect(String host, Int32 port, String user, String password) in C:\Users\Jeff\Documents\Visual Studio 2010\Projects\DialerAstro\DialerAstro\Form1.cs:line 47
```

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

using AsterNET;
using AsterNET.Manager;
using AsterNET.Manager.Action;
using AsterNET.Manager.Response;

namespace DialerAstro
{
    public partial class Form1 : Form
    {

        private ManagerConnection manager = null;
        private String curChannel;
        public string phoneExtension="5000";
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            MessageBox.Show(Connect("192.168.1.88", 5038, "admin", "1234"));   //"test", "1234"
            manager.NewChannel += manager_NewChannel; //event handler
            //Handle manager.NewChannel event
        }

        
        private string Connect(string host, int port, string user, string password)
        {
            manager = new ManagerConnection(host, port, user, password);

            manager.NewChannel += manager_NewChannel;

            manager.PingInterval = 0;

            try
            {
                manager.Login();
                return "Success";
            }
            catch (Exception ex)
            {
                manager.Logoff();
                return "Fail: " + ex.Message + "\n\n\n" + ex.StackTrace;
            }
        }

        
        void manager_NewChannel(object sender, AsterNET.Manager.Event.NewChannelEvent e)
        {
            if (e.CallerIdNum != phoneExtension)//userrow.number)
                return;

            curChannel = e.Channel;

        }

        void origionate(string extension, string callerID)
        {

            OriginateAction oc = new OriginateAction();

            oc.Priority = "1";
            oc.Exten = extension;  // extension to connect to
            oc.CallerId = callerID;
            oc.Context = "from-internal"; // in context
            oc.Channel = "SIP/peer/20005427"; // this is the channel and dialled first! Try this also: "SIP/401",
            oc.Timeout = 15000;
            oc.Async = true;
            ManagerResponse originateResponse = manager.SendAction(oc, oc.Timeout);
        }
    }
}
```

I tried adding this to manager_custom.conf and rebooting and using this code to sign in:
MessageBox.Show(Connect("192.168.1.88", 5038, "abc", "123"));

Here is the manager_custom.conf:
```
[abc]
secret = 123
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.0
permit = 192.168.211.129/255.255.255.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
```

**Comment by rex644** [comment]
I found the answer. I added a user to Settings>asterixmanager

Added permissions for my network:
192.168.1.0/255.255.255.0

**Comment by snailg** [comment]
How to set it?

I don't quite understand.

**Comment by Deantwo** [comment]
@snailg, please read the official Asterisk documentation about how to configure the **Manager.conf** file.
https://wiki.asterisk.org/wiki/display/AST/Asterisk+GUI#AsteriskGUI-Configuration
